language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
before_install:
- chmod a+x ./scripts/install.sh
- chmod a+x ./scripts/build.sh
install:
- ./scripts/install.sh
script:
- ./scripts/build.sh
